// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spot/v1/spot_service.proto

package spotv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/exchange-grpc/proto/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ViewMarketsRequest — запрос списка рынков.
// Роли пользователя извлекаются на сервере из JWT/metadata.
type ViewMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.CursorPagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsRequest) Reset() {
	*x = ViewMarketsRequest{}
	mi := &file_spot_v1_spot_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsRequest) ProtoMessage() {}

func (x *ViewMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_v1_spot_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsRequest) Descriptor() ([]byte, []int) {
	return file_spot_v1_spot_service_proto_rawDescGZIP(), []int{0}
}

func (x *ViewMarketsRequest) GetPagination() *v1.CursorPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ViewMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*v1.Market           `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	PageInfo      *v1.CursorPageInfo     `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse) Reset() {
	*x = ViewMarketsResponse{}
	mi := &file_spot_v1_spot_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse) ProtoMessage() {}

func (x *ViewMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_v1_spot_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse) Descriptor() ([]byte, []int) {
	return file_spot_v1_spot_service_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketsResponse) GetMarkets() []*v1.Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *ViewMarketsResponse) GetPageInfo() *v1.CursorPageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketRequest) Reset() {
	*x = GetMarketRequest{}
	mi := &file_spot_v1_spot_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketRequest) ProtoMessage() {}

func (x *GetMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_v1_spot_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketRequest.ProtoReflect.Descriptor instead.
func (*GetMarketRequest) Descriptor() ([]byte, []int) {
	return file_spot_v1_spot_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetMarketRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type GetMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *v1.Market             `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketResponse) Reset() {
	*x = GetMarketResponse{}
	mi := &file_spot_v1_spot_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketResponse) ProtoMessage() {}

func (x *GetMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_v1_spot_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketResponse.ProtoReflect.Descriptor instead.
func (*GetMarketResponse) Descriptor() ([]byte, []int) {
	return file_spot_v1_spot_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetMarketResponse) GetMarket() *v1.Market {
	if x != nil {
		return x.Market
	}
	return nil
}

var File_spot_v1_spot_service_proto protoreflect.FileDescriptor

const file_spot_v1_spot_service_proto_rawDesc = "" +
	"\n" +
	"\x1aspot/v1/spot_service.proto\x12\aspot.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16common/v1/market.proto\x1a\x1acommon/v1/pagination.proto\"Q\n" +
	"\x12ViewMarketsRequest\x12;\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.common.v1.CursorPaginationR\n" +
	"pagination\"z\n" +
	"\x13ViewMarketsResponse\x12+\n" +
	"\amarkets\x18\x01 \x03(\v2\x11.common.v1.MarketR\amarkets\x126\n" +
	"\tpage_info\x18\x02 \x01(\v2\x19.common.v1.CursorPageInfoR\bpageInfo\"8\n" +
	"\x10GetMarketRequest\x12$\n" +
	"\tmarket_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bmarketId\">\n" +
	"\x11GetMarketResponse\x12)\n" +
	"\x06market\x18\x01 \x01(\v2\x11.common.v1.MarketR\x06market2\x9b\x01\n" +
	"\vSpotService\x12H\n" +
	"\vViewMarkets\x12\x1b.spot.v1.ViewMarketsRequest\x1a\x1c.spot.v1.ViewMarketsResponse\x12B\n" +
	"\tGetMarket\x12\x19.spot.v1.GetMarketRequest\x1a\x1a.spot.v1.GetMarketResponseB2Z0github.com/exchange-grpc/proto/pb/spot/v1;spotv1b\x06proto3"

var (
	file_spot_v1_spot_service_proto_rawDescOnce sync.Once
	file_spot_v1_spot_service_proto_rawDescData []byte
)

func file_spot_v1_spot_service_proto_rawDescGZIP() []byte {
	file_spot_v1_spot_service_proto_rawDescOnce.Do(func() {
		file_spot_v1_spot_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spot_v1_spot_service_proto_rawDesc), len(file_spot_v1_spot_service_proto_rawDesc)))
	})
	return file_spot_v1_spot_service_proto_rawDescData
}

var file_spot_v1_spot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spot_v1_spot_service_proto_goTypes = []any{
	(*ViewMarketsRequest)(nil),  // 0: spot.v1.ViewMarketsRequest
	(*ViewMarketsResponse)(nil), // 1: spot.v1.ViewMarketsResponse
	(*GetMarketRequest)(nil),    // 2: spot.v1.GetMarketRequest
	(*GetMarketResponse)(nil),   // 3: spot.v1.GetMarketResponse
	(*v1.CursorPagination)(nil), // 4: common.v1.CursorPagination
	(*v1.Market)(nil),           // 5: common.v1.Market
	(*v1.CursorPageInfo)(nil),   // 6: common.v1.CursorPageInfo
}
var file_spot_v1_spot_service_proto_depIdxs = []int32{
	4, // 0: spot.v1.ViewMarketsRequest.pagination:type_name -> common.v1.CursorPagination
	5, // 1: spot.v1.ViewMarketsResponse.markets:type_name -> common.v1.Market
	6, // 2: spot.v1.ViewMarketsResponse.page_info:type_name -> common.v1.CursorPageInfo
	5, // 3: spot.v1.GetMarketResponse.market:type_name -> common.v1.Market
	0, // 4: spot.v1.SpotService.ViewMarkets:input_type -> spot.v1.ViewMarketsRequest
	2, // 5: spot.v1.SpotService.GetMarket:input_type -> spot.v1.GetMarketRequest
	1, // 6: spot.v1.SpotService.ViewMarkets:output_type -> spot.v1.ViewMarketsResponse
	3, // 7: spot.v1.SpotService.GetMarket:output_type -> spot.v1.GetMarketResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_spot_v1_spot_service_proto_init() }
func file_spot_v1_spot_service_proto_init() {
	if File_spot_v1_spot_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spot_v1_spot_service_proto_rawDesc), len(file_spot_v1_spot_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spot_v1_spot_service_proto_goTypes,
		DependencyIndexes: file_spot_v1_spot_service_proto_depIdxs,
		MessageInfos:      file_spot_v1_spot_service_proto_msgTypes,
	}.Build()
	File_spot_v1_spot_service_proto = out.File
	file_spot_v1_spot_service_proto_goTypes = nil
	file_spot_v1_spot_service_proto_depIdxs = nil
}
