// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: common/v1/market.proto

package commonv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Market — спотовый торговый рынок.
// Активность определяется полем enabled (active / inactive).
// id — торговый символ (BTC-USDT), не UUID; тот же контракт, что у GetMarketRequest.market_id.
type Market struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaseAsset    string                 `protobuf:"bytes,3,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QuoteAsset   string                 `protobuf:"bytes,4,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	Enabled      bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AllowedRoles []Role                 `protobuf:"varint,6,rep,packed,name=allowed_roles,json=allowedRoles,proto3,enum=common.v1.Role" json:"allowed_roles,omitempty"`
	// Минимальный объём ордера в базовом активе. Не required: отсутствие = лимит не задан.
	MinOrderSize *Decimal `protobuf:"bytes,7,opt,name=min_order_size,json=minOrderSize,proto3" json:"min_order_size,omitempty"`
	// Число знаков после запятой для quantity. 0 = не задано.
	QuantityPrecision uint32 `protobuf:"varint,8,opt,name=quantity_precision,json=quantityPrecision,proto3" json:"quantity_precision,omitempty"`
	// Минимальная сумма ордера в котировочном активе (не Money: currency там зафиксирован как USD).
	MinNotional   *Decimal `protobuf:"bytes,9,opt,name=min_notional,json=minNotional,proto3" json:"min_notional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_common_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_common_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *Market) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Market) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Market) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *Market) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *Market) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Market) GetAllowedRoles() []Role {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

func (x *Market) GetMinOrderSize() *Decimal {
	if x != nil {
		return x.MinOrderSize
	}
	return nil
}

func (x *Market) GetQuantityPrecision() uint32 {
	if x != nil {
		return x.QuantityPrecision
	}
	return 0
}

func (x *Market) GetMinNotional() *Decimal {
	if x != nil {
		return x.MinNotional
	}
	return nil
}

var File_common_v1_market_proto protoreflect.FileDescriptor

const file_common_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/market.proto\x12\tcommon.v1\x1a\x1bbuf/validate/validate.proto\x1a\x17common/v1/decimal.proto\x1a\x14common/v1/role.proto\"\xcb\x03\n" +
	"\x06Market\x120\n" +
	"\x02id\x18\x01 \x01(\tB \xbaH\x1dr\x1b\x10\x01\x18@2\x15^[A-Z0-9]+-[A-Z0-9]+$R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x04name\x125\n" +
	"\n" +
	"base_asset\x18\x03 \x01(\tB\x16\xbaH\x13r\x11\x10\x01\x18\x102\v^[A-Z0-9]+$R\tbaseAsset\x127\n" +
	"\vquote_asset\x18\x04 \x01(\tB\x16\xbaH\x13r\x11\x10\x01\x18\x102\v^[A-Z0-9]+$R\n" +
	"quoteAsset\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12E\n" +
	"\rallowed_roles\x18\x06 \x03(\x0e2\x0f.common.v1.RoleB\x0f\xbaH\f\x92\x01\t\"\a\x82\x01\x04\x10\x01 \x00R\fallowedRoles\x128\n" +
	"\x0emin_order_size\x18\a \x01(\v2\x12.common.v1.DecimalR\fminOrderSize\x12-\n" +
	"\x12quantity_precision\x18\b \x01(\rR\x11quantityPrecision\x125\n" +
	"\fmin_notional\x18\t \x01(\v2\x12.common.v1.DecimalR\vminNotionalB6Z4github.com/exchange-grpc/proto/pb/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_market_proto_rawDescOnce sync.Once
	file_common_v1_market_proto_rawDescData []byte
)

func file_common_v1_market_proto_rawDescGZIP() []byte {
	file_common_v1_market_proto_rawDescOnce.Do(func() {
		file_common_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_market_proto_rawDesc), len(file_common_v1_market_proto_rawDesc)))
	})
	return file_common_v1_market_proto_rawDescData
}

var file_common_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_market_proto_goTypes = []any{
	(*Market)(nil),  // 0: common.v1.Market
	(Role)(0),       // 1: common.v1.Role
	(*Decimal)(nil), // 2: common.v1.Decimal
}
var file_common_v1_market_proto_depIdxs = []int32{
	1, // 0: common.v1.Market.allowed_roles:type_name -> common.v1.Role
	2, // 1: common.v1.Market.min_order_size:type_name -> common.v1.Decimal
	2, // 2: common.v1.Market.min_notional:type_name -> common.v1.Decimal
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_v1_market_proto_init() }
func file_common_v1_market_proto_init() {
	if File_common_v1_market_proto != nil {
		return
	}
	file_common_v1_decimal_proto_init()
	file_common_v1_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_market_proto_rawDesc), len(file_common_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_market_proto_goTypes,
		DependencyIndexes: file_common_v1_market_proto_depIdxs,
		MessageInfos:      file_common_v1_market_proto_msgTypes,
	}.Build()
	File_common_v1_market_proto = out.File
	file_common_v1_market_proto_goTypes = nil
	file_common_v1_market_proto_depIdxs = nil
}
