// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/market.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Market — спотовый торговый рынок.
type Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaseAsset     string                 `protobuf:"bytes,3,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QuoteAsset    string                 `protobuf:"bytes,4,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	AllowedRoles  []string               `protobuf:"bytes,7,rep,name=allowed_roles,json=allowedRoles,proto3" json:"allowed_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_common_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_common_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *Market) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Market) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Market) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *Market) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *Market) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Market) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Market) GetAllowedRoles() []string {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

var File_common_v1_market_proto protoreflect.FileDescriptor

const file_common_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/market.proto\x12\tcommon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x01\n" +
	"\x06Market\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x03 \x01(\tR\tbaseAsset\x12\x1f\n" +
	"\vquote_asset\x18\x04 \x01(\tR\n" +
	"quoteAsset\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12#\n" +
	"\rallowed_roles\x18\a \x03(\tR\fallowedRolesB6Z4github.com/exchange-grpc/proto/pb/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_market_proto_rawDescOnce sync.Once
	file_common_v1_market_proto_rawDescData []byte
)

func file_common_v1_market_proto_rawDescGZIP() []byte {
	file_common_v1_market_proto_rawDescOnce.Do(func() {
		file_common_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_market_proto_rawDesc), len(file_common_v1_market_proto_rawDesc)))
	})
	return file_common_v1_market_proto_rawDescData
}

var file_common_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_market_proto_goTypes = []any{
	(*Market)(nil),                // 0: common.v1.Market
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_common_v1_market_proto_depIdxs = []int32{
	1, // 0: common.v1.Market.deleted_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_market_proto_init() }
func file_common_v1_market_proto_init() {
	if File_common_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_market_proto_rawDesc), len(file_common_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_market_proto_goTypes,
		DependencyIndexes: file_common_v1_market_proto_depIdxs,
		MessageInfos:      file_common_v1_market_proto_msgTypes,
	}.Build()
	File_common_v1_market_proto = out.File
	file_common_v1_market_proto_goTypes = nil
	file_common_v1_market_proto_depIdxs = nil
}
