// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/order_status.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderStatus — состояние ордера в жизненном цикле.
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_CREATED     OrderStatus = 1
	OrderStatus_ORDER_STATUS_FILLED      OrderStatus = 2
	OrderStatus_ORDER_STATUS_REJECTED    OrderStatus = 3
	OrderStatus_ORDER_STATUS_FAILED      OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_CREATED",
		2: "ORDER_STATUS_FILLED",
		3: "ORDER_STATUS_REJECTED",
		4: "ORDER_STATUS_FAILED",
		5: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_CREATED":     1,
		"ORDER_STATUS_FILLED":      2,
		"ORDER_STATUS_REJECTED":    3,
		"ORDER_STATUS_FAILED":      4,
		"ORDER_STATUS_CANCELLED":   5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_order_status_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_common_v1_order_status_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_order_status_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_order_status_proto protoreflect.FileDescriptor

const file_common_v1_order_status_proto_rawDesc = "" +
	"\n" +
	"\x1ccommon/v1/order_status.proto\x12\tcommon.v1*\xae\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_CREATED\x10\x01\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x02\x12\x19\n" +
	"\x15ORDER_STATUS_REJECTED\x10\x03\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x05B6Z4github.com/exchange-grpc/proto/pb/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_order_status_proto_rawDescOnce sync.Once
	file_common_v1_order_status_proto_rawDescData []byte
)

func file_common_v1_order_status_proto_rawDescGZIP() []byte {
	file_common_v1_order_status_proto_rawDescOnce.Do(func() {
		file_common_v1_order_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_order_status_proto_rawDesc), len(file_common_v1_order_status_proto_rawDesc)))
	})
	return file_common_v1_order_status_proto_rawDescData
}

var file_common_v1_order_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_order_status_proto_goTypes = []any{
	(OrderStatus)(0), // 0: common.v1.OrderStatus
}
var file_common_v1_order_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_order_status_proto_init() }
func file_common_v1_order_status_proto_init() {
	if File_common_v1_order_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_order_status_proto_rawDesc), len(file_common_v1_order_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_order_status_proto_goTypes,
		DependencyIndexes: file_common_v1_order_status_proto_depIdxs,
		EnumInfos:         file_common_v1_order_status_proto_enumTypes,
	}.Build()
	File_common_v1_order_status_proto = out.File
	file_common_v1_order_status_proto_goTypes = nil
	file_common_v1_order_status_proto_depIdxs = nil
}
