// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/order_side.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderSide — направление сделки.
type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_order_side_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_common_v1_order_side_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_order_side_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_order_side_proto protoreflect.FileDescriptor

const file_common_v1_order_side_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/v1/order_side.proto\x12\tcommon.v1*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02B6Z4github.com/exchange-grpc/proto/pb/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_order_side_proto_rawDescOnce sync.Once
	file_common_v1_order_side_proto_rawDescData []byte
)

func file_common_v1_order_side_proto_rawDescGZIP() []byte {
	file_common_v1_order_side_proto_rawDescOnce.Do(func() {
		file_common_v1_order_side_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_order_side_proto_rawDesc), len(file_common_v1_order_side_proto_rawDesc)))
	})
	return file_common_v1_order_side_proto_rawDescData
}

var file_common_v1_order_side_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_order_side_proto_goTypes = []any{
	(OrderSide)(0), // 0: common.v1.OrderSide
}
var file_common_v1_order_side_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_order_side_proto_init() }
func file_common_v1_order_side_proto_init() {
	if File_common_v1_order_side_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_order_side_proto_rawDesc), len(file_common_v1_order_side_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_order_side_proto_goTypes,
		DependencyIndexes: file_common_v1_order_side_proto_depIdxs,
		EnumInfos:         file_common_v1_order_side_proto_enumTypes,
	}.Build()
	File_common_v1_order_side_proto = out.File
	file_common_v1_order_side_proto_goTypes = nil
	file_common_v1_order_side_proto_depIdxs = nil
}
