// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/role.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role — роль пользователя в системе.
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_USER        Role = 1
	Role_ROLE_TRADER      Role = 2
	Role_ROLE_ADMIN       Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_TRADER",
		3: "ROLE_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_TRADER":      2,
		"ROLE_ADMIN":       3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_role_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_common_v1_role_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_role_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_role_proto protoreflect.FileDescriptor

const file_common_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x14common/v1/role.proto\x12\tcommon.v1*L\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x0f\n" +
	"\vROLE_TRADER\x10\x02\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x03B6Z4github.com/exchange-grpc/proto/pb/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_role_proto_rawDescOnce sync.Once
	file_common_v1_role_proto_rawDescData []byte
)

func file_common_v1_role_proto_rawDescGZIP() []byte {
	file_common_v1_role_proto_rawDescOnce.Do(func() {
		file_common_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_role_proto_rawDesc), len(file_common_v1_role_proto_rawDesc)))
	})
	return file_common_v1_role_proto_rawDescData
}

var file_common_v1_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_role_proto_goTypes = []any{
	(Role)(0), // 0: common.v1.Role
}
var file_common_v1_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_role_proto_init() }
func file_common_v1_role_proto_init() {
	if File_common_v1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_role_proto_rawDesc), len(file_common_v1_role_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_role_proto_goTypes,
		DependencyIndexes: file_common_v1_role_proto_depIdxs,
		EnumInfos:         file_common_v1_role_proto_enumTypes,
	}.Build()
	File_common_v1_role_proto = out.File
	file_common_v1_role_proto_goTypes = nil
	file_common_v1_role_proto_depIdxs = nil
}
