// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: order/v1/order_service.proto

package orderv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/exchange-grpc/proto/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateOrderRequest — параметры создания market-ордера.
// user_id и роли извлекаются на сервере из JWT/metadata.
type CreateOrderRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	MarketId string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side     v1.OrderSide           `protobuf:"varint,2,opt,name=side,proto3,enum=common.v1.OrderSide" json:"side,omitempty"`
	// Опционально для market-ордера. Если передано — вложенный Money проверяется (amount > 0).
	Price    *v1.Money   `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity *v1.Decimal `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Опционально: пустое значение пропускает правила (IGNORE_IF_ZERO_VALUE).
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CreateOrderRequest) GetSide() v1.OrderSide {
	if x != nil {
		return x.Side
	}
	return v1.OrderSide(0)
}

func (x *CreateOrderRequest) GetPrice() *v1.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *CreateOrderRequest) GetQuantity() *v1.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *CreateOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        v1.OrderStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=common.v1.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_v1_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResponse) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

type GetOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusRequest) Reset() {
	*x = GetOrderStatusRequest{}
	mi := &file_order_v1_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusRequest) ProtoMessage() {}

func (x *GetOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MarketId      string                 `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side          v1.OrderSide           `protobuf:"varint,4,opt,name=side,proto3,enum=common.v1.OrderSide" json:"side,omitempty"`
	Price         *v1.Money              `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      *v1.Decimal            `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status        v1.OrderStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=common.v1.OrderStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusResponse) Reset() {
	*x = GetOrderStatusResponse{}
	mi := &file_order_v1_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusResponse) ProtoMessage() {}

func (x *GetOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderStatusResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderStatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOrderStatusResponse) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *GetOrderStatusResponse) GetSide() v1.OrderSide {
	if x != nil {
		return x.Side
	}
	return v1.OrderSide(0)
}

func (x *GetOrderStatusResponse) GetPrice() *v1.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *GetOrderStatusResponse) GetQuantity() *v1.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *GetOrderStatusResponse) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

func (x *GetOrderStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetOrderStatusResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ListOrdersRequest — список ордеров текущего пользователя (user_id из JWT).
// market_id и status опциональны: пустое значение не фильтрует.
type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.CursorPagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	MarketId      *string                `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3,oneof" json:"market_id,omitempty"`
	Status        *v1.OrderStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=common.v1.OrderStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_v1_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersRequest) GetPagination() *v1.CursorPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListOrdersRequest) GetMarketId() string {
	if x != nil && x.MarketId != nil {
		return *x.MarketId
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() v1.OrderStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return v1.OrderStatus(0)
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderSummary        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	PageInfo      *v1.CursorPageInfo     `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_v1_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersResponse) GetOrders() []*OrderSummary {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetPageInfo() *v1.CursorPageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type OrderSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MarketId      string                 `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side          v1.OrderSide           `protobuf:"varint,3,opt,name=side,proto3,enum=common.v1.OrderSide" json:"side,omitempty"`
	Price         *v1.Money              `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      *v1.Decimal            `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status        v1.OrderStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=common.v1.OrderStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSummary) Reset() {
	*x = OrderSummary{}
	mi := &file_order_v1_order_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSummary) ProtoMessage() {}

func (x *OrderSummary) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSummary.ProtoReflect.Descriptor instead.
func (*OrderSummary) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{6}
}

func (x *OrderSummary) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderSummary) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *OrderSummary) GetSide() v1.OrderSide {
	if x != nil {
		return x.Side
	}
	return v1.OrderSide(0)
}

func (x *OrderSummary) GetPrice() *v1.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OrderSummary) GetQuantity() *v1.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *OrderSummary) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

func (x *OrderSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderSummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StreamOrderUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrderUpdatesRequest) Reset() {
	*x = StreamOrderUpdatesRequest{}
	mi := &file_order_v1_order_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderUpdatesRequest) ProtoMessage() {}

func (x *StreamOrderUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamOrderUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{7}
}

func (x *StreamOrderUpdatesRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// StreamUserOrderUpdatesRequest — поток обновлений всех ордеров текущего пользователя (user_id из JWT).
// Фильтры опциональны: пустое значение не сужает поток.
type StreamUserOrderUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      *string                `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3,oneof" json:"market_id,omitempty"`
	Status        *v1.OrderStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=common.v1.OrderStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUserOrderUpdatesRequest) Reset() {
	*x = StreamUserOrderUpdatesRequest{}
	mi := &file_order_v1_order_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUserOrderUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUserOrderUpdatesRequest) ProtoMessage() {}

func (x *StreamUserOrderUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUserOrderUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamUserOrderUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{8}
}

func (x *StreamUserOrderUpdatesRequest) GetMarketId() string {
	if x != nil && x.MarketId != nil {
		return *x.MarketId
	}
	return ""
}

func (x *StreamUserOrderUpdatesRequest) GetStatus() v1.OrderStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return v1.OrderStatus(0)
}

type OrderUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        v1.OrderStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=common.v1.OrderStatus" json:"status,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdate) Reset() {
	*x = OrderUpdate{}
	mi := &file_order_v1_order_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdate) ProtoMessage() {}

func (x *OrderUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdate.ProtoReflect.Descriptor instead.
func (*OrderUpdate) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{9}
}

func (x *OrderUpdate) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderUpdate) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

func (x *OrderUpdate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_order_v1_order_service_proto protoreflect.FileDescriptor

const file_order_v1_order_service_proto_rawDesc = "" +
	"\n" +
	"\x1corder/v1/order_service.proto\x12\border.v1\x1a\x1bbuf/validate/validate.proto\x1a\x17common/v1/decimal.proto\x1a\x15common/v1/money.proto\x1a\x1acommon/v1/order_side.proto\x1a\x1ccommon/v1/order_status.proto\x1a\x1acommon/v1/pagination.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x02\n" +
	"\x12CreateOrderRequest\x12=\n" +
	"\tmarket_id\x18\x01 \x01(\tB \xbaH\x1dr\x1b\x10\x01\x18@2\x15^[A-Z0-9]+-[A-Z0-9]+$R\bmarketId\x124\n" +
	"\x04side\x18\x02 \x01(\x0e2\x14.common.v1.OrderSideB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04side\x12&\n" +
	"\x05price\x18\x03 \x01(\v2\x10.common.v1.MoneyR\x05price\x126\n" +
	"\bquantity\x18\x04 \x01(\v2\x12.common.v1.DecimalB\x06\xbaH\x03\xc8\x01\x01R\bquantity\x12H\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tB\x1f\xbaH\x1c\xd8\x01\x01r\x17\x10\x01\x18\x80\x012\x10^[A-Za-z0-9_-]+$R\x0eidempotencyKey\"j\n" +
	"\x13CreateOrderResponse\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aorderId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.common.v1.OrderStatusR\x06status\"<\n" +
	"\x15GetOrderStatusRequest\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aorderId\"\xa5\x03\n" +
	"\x16GetOrderStatusResponse\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aorderId\x12!\n" +
	"\auser_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\tR\bmarketId\x12(\n" +
	"\x04side\x18\x04 \x01(\x0e2\x14.common.v1.OrderSideR\x04side\x12&\n" +
	"\x05price\x18\x05 \x01(\v2\x10.common.v1.MoneyR\x05price\x12.\n" +
	"\bquantity\x18\x06 \x01(\v2\x12.common.v1.DecimalR\bquantity\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.common.v1.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf4\x01\n" +
	"\x11ListOrdersRequest\x12;\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.common.v1.CursorPaginationR\n" +
	"pagination\x12E\n" +
	"\tmarket_id\x18\x02 \x01(\tB#\xbaH \xd8\x01\x01r\x1b\x10\x01\x18@2\x15^[A-Z0-9]+-[A-Z0-9]+$H\x00R\bmarketId\x88\x01\x01\x12B\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.common.v1.OrderStatusB\r\xbaH\n" +
	"\xd8\x01\x01\x82\x01\x04\x10\x01 \x00H\x01R\x06status\x88\x01\x01B\f\n" +
	"\n" +
	"_market_idB\t\n" +
	"\a_status\"|\n" +
	"\x12ListOrdersResponse\x12.\n" +
	"\x06orders\x18\x01 \x03(\v2\x16.order.v1.OrderSummaryR\x06orders\x126\n" +
	"\tpage_info\x18\x02 \x01(\v2\x19.common.v1.CursorPageInfoR\bpageInfo\"\xf8\x02\n" +
	"\fOrderSummary\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aorderId\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x12(\n" +
	"\x04side\x18\x03 \x01(\x0e2\x14.common.v1.OrderSideR\x04side\x12&\n" +
	"\x05price\x18\x04 \x01(\v2\x10.common.v1.MoneyR\x05price\x12.\n" +
	"\bquantity\x18\x05 \x01(\v2\x12.common.v1.DecimalR\bquantity\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.common.v1.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"@\n" +
	"\x19StreamOrderUpdatesRequest\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aorderId\"\xc3\x01\n" +
	"\x1dStreamUserOrderUpdatesRequest\x12E\n" +
	"\tmarket_id\x18\x01 \x01(\tB#\xbaH \xd8\x01\x01r\x1b\x10\x01\x18@2\x15^[A-Z0-9]+-[A-Z0-9]+$H\x00R\bmarketId\x88\x01\x01\x12B\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.common.v1.OrderStatusB\r\xbaH\n" +
	"\xd8\x01\x01\x82\x01\x04\x10\x01 \x00H\x01R\x06status\x88\x01\x01B\f\n" +
	"\n" +
	"_market_idB\t\n" +
	"\a_status\"\x9d\x01\n" +
	"\vOrderUpdate\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aorderId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.common.v1.OrderStatusR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xa8\x03\n" +
	"\fOrderService\x12J\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\x12S\n" +
	"\x0eGetOrderStatus\x12\x1f.order.v1.GetOrderStatusRequest\x1a .order.v1.GetOrderStatusResponse\x12G\n" +
	"\n" +
	"ListOrders\x12\x1b.order.v1.ListOrdersRequest\x1a\x1c.order.v1.ListOrdersResponse\x12R\n" +
	"\x12StreamOrderUpdates\x12#.order.v1.StreamOrderUpdatesRequest\x1a\x15.order.v1.OrderUpdate0\x01\x12Z\n" +
	"\x16StreamUserOrderUpdates\x12'.order.v1.StreamUserOrderUpdatesRequest\x1a\x15.order.v1.OrderUpdate0\x01B4Z2github.com/exchange-grpc/proto/pb/order/v1;orderv1b\x06proto3"

var (
	file_order_v1_order_service_proto_rawDescOnce sync.Once
	file_order_v1_order_service_proto_rawDescData []byte
)

func file_order_v1_order_service_proto_rawDescGZIP() []byte {
	file_order_v1_order_service_proto_rawDescOnce.Do(func() {
		file_order_v1_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_service_proto_rawDesc), len(file_order_v1_order_service_proto_rawDesc)))
	})
	return file_order_v1_order_service_proto_rawDescData
}

var file_order_v1_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_order_v1_order_service_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),            // 0: order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),           // 1: order.v1.CreateOrderResponse
	(*GetOrderStatusRequest)(nil),         // 2: order.v1.GetOrderStatusRequest
	(*GetOrderStatusResponse)(nil),        // 3: order.v1.GetOrderStatusResponse
	(*ListOrdersRequest)(nil),             // 4: order.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),            // 5: order.v1.ListOrdersResponse
	(*OrderSummary)(nil),                  // 6: order.v1.OrderSummary
	(*StreamOrderUpdatesRequest)(nil),     // 7: order.v1.StreamOrderUpdatesRequest
	(*StreamUserOrderUpdatesRequest)(nil), // 8: order.v1.StreamUserOrderUpdatesRequest
	(*OrderUpdate)(nil),                   // 9: order.v1.OrderUpdate
	(v1.OrderSide)(0),                     // 10: common.v1.OrderSide
	(*v1.Money)(nil),                      // 11: common.v1.Money
	(*v1.Decimal)(nil),                    // 12: common.v1.Decimal
	(v1.OrderStatus)(0),                   // 13: common.v1.OrderStatus
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
	(*v1.CursorPagination)(nil),           // 15: common.v1.CursorPagination
	(*v1.CursorPageInfo)(nil),             // 16: common.v1.CursorPageInfo
}
var file_order_v1_order_service_proto_depIdxs = []int32{
	10, // 0: order.v1.CreateOrderRequest.side:type_name -> common.v1.OrderSide
	11, // 1: order.v1.CreateOrderRequest.price:type_name -> common.v1.Money
	12, // 2: order.v1.CreateOrderRequest.quantity:type_name -> common.v1.Decimal
	13, // 3: order.v1.CreateOrderResponse.status:type_name -> common.v1.OrderStatus
	10, // 4: order.v1.GetOrderStatusResponse.side:type_name -> common.v1.OrderSide
	11, // 5: order.v1.GetOrderStatusResponse.price:type_name -> common.v1.Money
	12, // 6: order.v1.GetOrderStatusResponse.quantity:type_name -> common.v1.Decimal
	13, // 7: order.v1.GetOrderStatusResponse.status:type_name -> common.v1.OrderStatus
	14, // 8: order.v1.GetOrderStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 9: order.v1.GetOrderStatusResponse.updated_at:type_name -> google.protobuf.Timestamp
	15, // 10: order.v1.ListOrdersRequest.pagination:type_name -> common.v1.CursorPagination
	13, // 11: order.v1.ListOrdersRequest.status:type_name -> common.v1.OrderStatus
	6,  // 12: order.v1.ListOrdersResponse.orders:type_name -> order.v1.OrderSummary
	16, // 13: order.v1.ListOrdersResponse.page_info:type_name -> common.v1.CursorPageInfo
	10, // 14: order.v1.OrderSummary.side:type_name -> common.v1.OrderSide
	11, // 15: order.v1.OrderSummary.price:type_name -> common.v1.Money
	12, // 16: order.v1.OrderSummary.quantity:type_name -> common.v1.Decimal
	13, // 17: order.v1.OrderSummary.status:type_name -> common.v1.OrderStatus
	14, // 18: order.v1.OrderSummary.created_at:type_name -> google.protobuf.Timestamp
	14, // 19: order.v1.OrderSummary.updated_at:type_name -> google.protobuf.Timestamp
	13, // 20: order.v1.StreamUserOrderUpdatesRequest.status:type_name -> common.v1.OrderStatus
	13, // 21: order.v1.OrderUpdate.status:type_name -> common.v1.OrderStatus
	14, // 22: order.v1.OrderUpdate.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 23: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	2,  // 24: order.v1.OrderService.GetOrderStatus:input_type -> order.v1.GetOrderStatusRequest
	4,  // 25: order.v1.OrderService.ListOrders:input_type -> order.v1.ListOrdersRequest
	7,  // 26: order.v1.OrderService.StreamOrderUpdates:input_type -> order.v1.StreamOrderUpdatesRequest
	8,  // 27: order.v1.OrderService.StreamUserOrderUpdates:input_type -> order.v1.StreamUserOrderUpdatesRequest
	1,  // 28: order.v1.OrderService.CreateOrder:output_type -> order.v1.CreateOrderResponse
	3,  // 29: order.v1.OrderService.GetOrderStatus:output_type -> order.v1.GetOrderStatusResponse
	5,  // 30: order.v1.OrderService.ListOrders:output_type -> order.v1.ListOrdersResponse
	9,  // 31: order.v1.OrderService.StreamOrderUpdates:output_type -> order.v1.OrderUpdate
	9,  // 32: order.v1.OrderService.StreamUserOrderUpdates:output_type -> order.v1.OrderUpdate
	28, // [28:33] is the sub-list for method output_type
	23, // [23:28] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_order_v1_order_service_proto_init() }
func file_order_v1_order_service_proto_init() {
	if File_order_v1_order_service_proto != nil {
		return
	}
	file_order_v1_order_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_order_v1_order_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_service_proto_rawDesc), len(file_order_v1_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_service_proto_goTypes,
		DependencyIndexes: file_order_v1_order_service_proto_depIdxs,
		MessageInfos:      file_order_v1_order_service_proto_msgTypes,
	}.Build()
	File_order_v1_order_service_proto = out.File
	file_order_v1_order_service_proto_goTypes = nil
	file_order_v1_order_service_proto_depIdxs = nil
}
