// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: order/v1/order_service.proto

package orderv1

import (
	v1 "github.com/exchange-grpc/proto/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateOrderRequest — параметры создания market-ордера.
// user_id и роли извлекаются на сервере из JWT/metadata.
type CreateOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MarketId       string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side           v1.OrderSide           `protobuf:"varint,2,opt,name=side,proto3,enum=common.v1.OrderSide" json:"side,omitempty"`
	Price          *v1.Money              `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity       *v1.Decimal            `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CreateOrderRequest) GetSide() v1.OrderSide {
	if x != nil {
		return x.Side
	}
	return v1.OrderSide(0)
}

func (x *CreateOrderRequest) GetPrice() *v1.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *CreateOrderRequest) GetQuantity() *v1.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *CreateOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// CreateOrderResponse — результат создания ордера.
type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *v1.Uuid               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        v1.OrderStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=common.v1.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_v1_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderId() *v1.Uuid {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *CreateOrderResponse) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

// GetOrderStatusRequest — запрос статуса ордера.
type GetOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *v1.Uuid               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusRequest) Reset() {
	*x = GetOrderStatusRequest{}
	mi := &file_order_v1_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusRequest) ProtoMessage() {}

func (x *GetOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderStatusRequest) GetOrderId() *v1.Uuid {
	if x != nil {
		return x.OrderId
	}
	return nil
}

// GetOrderStatusResponse — текущее состояние ордера.
type GetOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *v1.Uuid               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        *v1.Uuid               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MarketId      string                 `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side          v1.OrderSide           `protobuf:"varint,4,opt,name=side,proto3,enum=common.v1.OrderSide" json:"side,omitempty"`
	Price         *v1.Money              `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      *v1.Decimal            `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status        v1.OrderStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=common.v1.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusResponse) Reset() {
	*x = GetOrderStatusResponse{}
	mi := &file_order_v1_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusResponse) ProtoMessage() {}

func (x *GetOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderStatusResponse) GetOrderId() *v1.Uuid {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *GetOrderStatusResponse) GetUserId() *v1.Uuid {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetOrderStatusResponse) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *GetOrderStatusResponse) GetSide() v1.OrderSide {
	if x != nil {
		return x.Side
	}
	return v1.OrderSide(0)
}

func (x *GetOrderStatusResponse) GetPrice() *v1.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *GetOrderStatusResponse) GetQuantity() *v1.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *GetOrderStatusResponse) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

// StreamOrderUpdatesRequest — подписка на обновления статуса ордера.
type StreamOrderUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *v1.Uuid               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrderUpdatesRequest) Reset() {
	*x = StreamOrderUpdatesRequest{}
	mi := &file_order_v1_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderUpdatesRequest) ProtoMessage() {}

func (x *StreamOrderUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamOrderUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *StreamOrderUpdatesRequest) GetOrderId() *v1.Uuid {
	if x != nil {
		return x.OrderId
	}
	return nil
}

// OrderUpdate — событие изменения статуса ордера.
type OrderUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *v1.Uuid               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        v1.OrderStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=common.v1.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdate) Reset() {
	*x = OrderUpdate{}
	mi := &file_order_v1_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdate) ProtoMessage() {}

func (x *OrderUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdate.ProtoReflect.Descriptor instead.
func (*OrderUpdate) Descriptor() ([]byte, []int) {
	return file_order_v1_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *OrderUpdate) GetOrderId() *v1.Uuid {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *OrderUpdate) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

var File_order_v1_order_service_proto protoreflect.FileDescriptor

const file_order_v1_order_service_proto_rawDesc = "" +
	"\n" +
	"\x1corder/v1/order_service.proto\x12\border.v1\x1a\x17common/v1/decimal.proto\x1a\x15common/v1/money.proto\x1a\x1acommon/v1/order_side.proto\x1a\x1ccommon/v1/order_status.proto\x1a\x14common/v1/uuid.proto\"\xdc\x01\n" +
	"\x12CreateOrderRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12(\n" +
	"\x04side\x18\x02 \x01(\x0e2\x14.common.v1.OrderSideR\x04side\x12&\n" +
	"\x05price\x18\x03 \x01(\v2\x10.common.v1.MoneyR\x05price\x12.\n" +
	"\bquantity\x18\x04 \x01(\v2\x12.common.v1.DecimalR\bquantity\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"q\n" +
	"\x13CreateOrderResponse\x12*\n" +
	"\border_id\x18\x01 \x01(\v2\x0f.common.v1.UuidR\aorderId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.common.v1.OrderStatusR\x06status\"C\n" +
	"\x15GetOrderStatusRequest\x12*\n" +
	"\border_id\x18\x01 \x01(\v2\x0f.common.v1.UuidR\aorderId\"\xbd\x02\n" +
	"\x16GetOrderStatusResponse\x12*\n" +
	"\border_id\x18\x01 \x01(\v2\x0f.common.v1.UuidR\aorderId\x12(\n" +
	"\auser_id\x18\x02 \x01(\v2\x0f.common.v1.UuidR\x06userId\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\tR\bmarketId\x12(\n" +
	"\x04side\x18\x04 \x01(\x0e2\x14.common.v1.OrderSideR\x04side\x12&\n" +
	"\x05price\x18\x05 \x01(\v2\x10.common.v1.MoneyR\x05price\x12.\n" +
	"\bquantity\x18\x06 \x01(\v2\x12.common.v1.DecimalR\bquantity\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.common.v1.OrderStatusR\x06status\"G\n" +
	"\x19StreamOrderUpdatesRequest\x12*\n" +
	"\border_id\x18\x01 \x01(\v2\x0f.common.v1.UuidR\aorderId\"i\n" +
	"\vOrderUpdate\x12*\n" +
	"\border_id\x18\x01 \x01(\v2\x0f.common.v1.UuidR\aorderId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.common.v1.OrderStatusR\x06status2\x83\x02\n" +
	"\fOrderService\x12J\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\x12S\n" +
	"\x0eGetOrderStatus\x12\x1f.order.v1.GetOrderStatusRequest\x1a .order.v1.GetOrderStatusResponse\x12R\n" +
	"\x12StreamOrderUpdates\x12#.order.v1.StreamOrderUpdatesRequest\x1a\x15.order.v1.OrderUpdate0\x01B4Z2github.com/exchange-grpc/proto/pb/order/v1;orderv1b\x06proto3"

var (
	file_order_v1_order_service_proto_rawDescOnce sync.Once
	file_order_v1_order_service_proto_rawDescData []byte
)

func file_order_v1_order_service_proto_rawDescGZIP() []byte {
	file_order_v1_order_service_proto_rawDescOnce.Do(func() {
		file_order_v1_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_service_proto_rawDesc), len(file_order_v1_order_service_proto_rawDesc)))
	})
	return file_order_v1_order_service_proto_rawDescData
}

var file_order_v1_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_order_v1_order_service_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),        // 0: order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),       // 1: order.v1.CreateOrderResponse
	(*GetOrderStatusRequest)(nil),     // 2: order.v1.GetOrderStatusRequest
	(*GetOrderStatusResponse)(nil),    // 3: order.v1.GetOrderStatusResponse
	(*StreamOrderUpdatesRequest)(nil), // 4: order.v1.StreamOrderUpdatesRequest
	(*OrderUpdate)(nil),               // 5: order.v1.OrderUpdate
	(v1.OrderSide)(0),                 // 6: common.v1.OrderSide
	(*v1.Money)(nil),                  // 7: common.v1.Money
	(*v1.Decimal)(nil),                // 8: common.v1.Decimal
	(*v1.Uuid)(nil),                   // 9: common.v1.Uuid
	(v1.OrderStatus)(0),               // 10: common.v1.OrderStatus
}
var file_order_v1_order_service_proto_depIdxs = []int32{
	6,  // 0: order.v1.CreateOrderRequest.side:type_name -> common.v1.OrderSide
	7,  // 1: order.v1.CreateOrderRequest.price:type_name -> common.v1.Money
	8,  // 2: order.v1.CreateOrderRequest.quantity:type_name -> common.v1.Decimal
	9,  // 3: order.v1.CreateOrderResponse.order_id:type_name -> common.v1.Uuid
	10, // 4: order.v1.CreateOrderResponse.status:type_name -> common.v1.OrderStatus
	9,  // 5: order.v1.GetOrderStatusRequest.order_id:type_name -> common.v1.Uuid
	9,  // 6: order.v1.GetOrderStatusResponse.order_id:type_name -> common.v1.Uuid
	9,  // 7: order.v1.GetOrderStatusResponse.user_id:type_name -> common.v1.Uuid
	6,  // 8: order.v1.GetOrderStatusResponse.side:type_name -> common.v1.OrderSide
	7,  // 9: order.v1.GetOrderStatusResponse.price:type_name -> common.v1.Money
	8,  // 10: order.v1.GetOrderStatusResponse.quantity:type_name -> common.v1.Decimal
	10, // 11: order.v1.GetOrderStatusResponse.status:type_name -> common.v1.OrderStatus
	9,  // 12: order.v1.StreamOrderUpdatesRequest.order_id:type_name -> common.v1.Uuid
	9,  // 13: order.v1.OrderUpdate.order_id:type_name -> common.v1.Uuid
	10, // 14: order.v1.OrderUpdate.status:type_name -> common.v1.OrderStatus
	0,  // 15: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	2,  // 16: order.v1.OrderService.GetOrderStatus:input_type -> order.v1.GetOrderStatusRequest
	4,  // 17: order.v1.OrderService.StreamOrderUpdates:input_type -> order.v1.StreamOrderUpdatesRequest
	1,  // 18: order.v1.OrderService.CreateOrder:output_type -> order.v1.CreateOrderResponse
	3,  // 19: order.v1.OrderService.GetOrderStatus:output_type -> order.v1.GetOrderStatusResponse
	5,  // 20: order.v1.OrderService.StreamOrderUpdates:output_type -> order.v1.OrderUpdate
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_order_v1_order_service_proto_init() }
func file_order_v1_order_service_proto_init() {
	if File_order_v1_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_service_proto_rawDesc), len(file_order_v1_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_service_proto_goTypes,
		DependencyIndexes: file_order_v1_order_service_proto_depIdxs,
		MessageInfos:      file_order_v1_order_service_proto_msgTypes,
	}.Build()
	File_order_v1_order_service_proto = out.File
	file_order_v1_order_service_proto_goTypes = nil
	file_order_v1_order_service_proto_depIdxs = nil
}
