global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: spot-instrument-service
    static_configs:
      - targets: ["spot-instrument:9090"]

  - job_name: order-service
    static_configs:
      - targets: ["order-service:9091"]
